'use client';
import {useState, type ReactNode} from 'react';
import {ArrowRight, ArrowUpRight, Check, CircleHelp, Layers, Link2, Plus, RotateCcw, ScanText, ShieldCheck, Sparkles, X, ZoomIn} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import Image from 'next/image';
import {stageData} from './story-data';
import {ClosingNote} from './story-experience';
import {CaptureMechanism, ClarifyMechanism, OrganizeMechanism, MemoryMechanism, ReliabilityMechanism} from './story-mechanisms';
type Open=(id:string)=>void;
export function More({id,children,open}:{id:string;children:ReactNode;open:Open}){return <button className="text-link" onClick={()=>open(id)}>{children}<ArrowUpRight size={16}/></button>}
export function Journey({active}:{active:string}){return <div className="journey-wrap"><div className="journey"><p>一条记录的理想路径</p><ol>{stageData.map((s,i)=><li key={s.title}><a href={['#choices','#clarify','#organize','#memory'][i]} aria-current={active===['choices','clarify','organize','memory'][i]?'step':undefined}><span className="journey-number">{i+1}</span><span>{s.title}</span><ArrowRight size={15}/></a></li>)}</ol></div></div>}
export function Entry({open,zoom}:{open:Open;zoom:(src:string,title:string)=>void}){
 const [mode,setMode]=useState('record');
 const entries=[{id:'record',title:'有新念头，马上记',role:'核心入口',text:'入口先接住内容。还没写下一句话，就不急着让用户研究 AI 的全部能力。',anchor:'记备忘'},{id:'todo',title:'打开后，知道接着做什么',role:'常驻模块',text:'待办把“要做的事”摆在眼前；上次编辑帮忙接回刚才的思路。',anchor:'待办 · 上次编辑'},{id:'library',title:'需要找资料时，再进信息库',role:'收纳入口',text:'完整列表承接检索与管理。入口文字提示帮助用户知道还能往哪里走。',anchor:'完整备忘录列表'}];
 return <section className="section-wrap entry-section" id="choices" data-scene="entry"><div className="entry-visual"><div className="visual-topline"><span>打开 App 的第一眼</span><span>V2 设计稿</span></div><button className="screen-button entry-screen" onClick={()=>zoom('/ui/entry.png','生活速记助手 · V2 设计稿')} aria-label="查看生活速记助手完整设计图"><Image src="/ui/entry.png" alt="生活速记助手完整设计稿，包含记备忘、待办、上次编辑和信息库入口" width="1170" height="2532" loading="lazy"/><span className="zoom-hint"><ZoomIn size={14}/>查看完整图</span></button><p className="figure-note">设计稿中的广场入口未沿用至当前测试版。</p></div><div className="entry-copy"><h2>第一步，先接住<br/>那个转瞬即逝的念头。</h2><p className="body-copy">下班路上想起要买拖把，打开 App 就应该能记。等回到家，再从待办和上次编辑接着做。</p><div className="choice-list" aria-label="选择打开 App 的目的">{entries.map(e=><button className={mode===e.id?'choice-row selected':'choice-row'} onClick={()=>setMode(e.id)} key={e.id} aria-pressed={mode===e.id}><div className="choice-heading"><span>{e.title}</span><span className="choice-indicator">{mode===e.id?<MinusIcon/>:<Plus size={16}/>}</span></div>{mode===e.id&&<div className="choice-body"><span className="role-label">{e.role} · {e.anchor}</span><p>{e.text}</p></div>}</button>)}</div><More id="entry" open={open}>查看首页的角色分工</More></div></section>
}
function MinusIcon(){return <span aria-hidden="true">−</span>}
export function Capture({open}:{open:Open}){return <div className="capture-strip section-wrap"><div><ScanText size={23}/><h3>聊天里的约定，也能顺手留下。</h3><p>搬家师傅发来报价，截图就能接住信息。<br/>先确认是哪张图，再识别和生成；失败了，还能回来处理。</p></div><CaptureMechanism/><More id="capture" open={open}>为什么多留一次确认</More></div>}
export function Clarify({open}:{open:Open}){
 const [selected,setSelected]=useState(''),[manual,setManual]=useState(''),[saved,setSaved]=useState(false);
 const value=selected==='manual'?manual.trim():selected;const preserve=value==='preserve';
 const reset=()=>{setSelected('');setManual('');setSaved(false)};
 return <section className="clarify-section" id="clarify" data-scene="clarify"><div className="clarify-inner section-wrap"><div className="clarify-copy"><p className="section-kicker">到这里，AI 需要先补问一句</p><h2>“旺财”是谁，<br/>AI 不能替你猜。</h2><p className="body-copy">给小狗换窝，和给仓鼠换窝，准备的东西差很多。<br/>用户没有写出的生活常识，AI 需要先向本人确认。</p><div className="design-note"><span>我的选择</span><p>把含糊处挑出来，<br/>让用户轻轻点一下。</p></div><p className="quiet-copy">只追问会改变结果的关键缺口。<br/>能点选，就少让人重新打一遍字。</p><ClarifyMechanism selected={selected} saved={saved}/><More id="clarify" open={open}>原始界面与取舍依据</More></div><div className="clarify-demo demo-surface"><div className="demo-top"><span>试着补全这句话</span><span>交互示意</span></div><p className="original-sentence">周末搬家，给 <mark>旺财</mark> 换窝。</p><div className="question"><span className="round-icon"><CircleHelp size={17}/></span><div><strong>这里的“旺财”是？</strong><p>选一个，看看这句记录会怎样变化。</p></div></div><div className="answer-grid">{[['小狗','家里的小狗'],['仓鼠','家里的仓鼠'],['manual','我来补充'],['preserve','保留原词']].map(([v,t])=><button key={v} onClick={()=>{setSelected(v);setSaved(false)}} aria-pressed={selected===v} className={selected===v?'answer active':'answer'}>{t}{selected===v&&<Check size={15}/>}</button>)}</div>{selected==='manual'&&<label className="manual-label">旺财是<input value={manual} maxLength={24} placeholder="例如：我的小猫" onChange={e=>{setManual(e.target.value);setSaved(false)}}/></label>}<div className="rewrite-preview" key={`${selected}-${saved}`} data-confirmed={saved} aria-live="polite"><span>{saved?'已在演示中确认':value?'确认前，先看一眼':'你的原文会先留着'}</span><p>{value&&!preserve?`周末搬家，给${value}旺财换窝。`:'周末搬家，给旺财换窝。'}</p><small>{saved?'这次选择只影响网页示例。':preserve?'本次不改动原句，也不替你补充事实。':value?'只有你确认，这个补充才成立。':'AI 提供候选，具体是谁，由你决定。'}</small></div><div className="demo-actions"><button className="plain-button" onClick={reset}><RotateCcw size={14}/>重来一次</button><button className="solid-button" disabled={!value||saved} onClick={()=>setSaved(true)}>{saved?<><Check size={15}/>已确认</>:preserve?'确认保留':'确认这次补充'}</button></div><p className="demo-footnote">预设示例 · 包含预览、保留原词的补充交互方案</p></div></div></section>
}
export function Organize({open,zoom}:{open:Open;zoom:(src:string,title:string)=>void}){
 const [chosen,setChosen]=useState<string[]>(['水电表']),[saved,setSaved]=useState(false);
 const items=[{id:'水电表',title:'搬走前，拍照留存水电表读数',why:'退租核对时更方便。'},{id:'随身包',title:'把当天要用的东西单独装一袋',why:'不用到了新家再拆所有箱子。'},{id:'押金',title:'提前核对租约里的押金条款',why:'减少最后一天临时确认的事情。'}];
 return <section className="section-wrap organize-section" id="organize" data-scene="organize"><div className="center-heading"><h2>它替你多想一步。<br/>你只留下用得上的部分。</h2><p className="section-lead">买拖把是已经决定的事，拍水电表是 AI 提醒的事。<br/>两者分开放，才不会把建议悄悄变成你的决定。</p></div><div className="organize-layout"><div className="information-stack"><OrganizeMechanism count={chosen.length} saved={saved}/><div className="original-record-note"><span>原文一直在</span><p>周末搬家，给旺财换窝，买拖把。</p></div><button className="text-link" onClick={()=>zoom('/ui/organize.png','智能整理 · 完整长界面设计稿')}>对照完整产品界面<ZoomIn size={15}/></button></div><div className="suggestion-demo demo-surface"><div className="demo-top"><span><Sparkles size={16}/>AI 想到的补充</span><span>交互示意</span></div>{items.map(item=><label aria-label={item.title} className={chosen.includes(item.id)?'suggestion chosen':'suggestion'} key={item.id}><input type="checkbox" checked={chosen.includes(item.id)} onChange={()=>{setChosen(p=>p.includes(item.id)?p.filter(x=>x!==item.id):[...p,item.id]);setSaved(false)}}/><span><strong>{item.title}</strong><small>{item.why}</small></span></label>)}<div className="saved-receipt" key={String(saved)} data-confirmed={saved} aria-live="polite">{saved?<><Check size={16}/><div><strong>{chosen.length?`在演示中留下 ${chosen.length} 条建议`:'本次没有添加建议'}</strong><p>{chosen.length?items.filter(i=>chosen.includes(i.id)).map(i=>i.title).join('；'):'原记录继续保留。'}</p></div></>:<span>当前选择 {chosen.length} 条，可以只保留你需要的。</span>}</div><div className="demo-actions"><button className="plain-button" onClick={()=>{setChosen([]);setSaved(false)}}>全部不选</button><button className="solid-button" onClick={()=>setSaved(true)}>{saved?'重新确认':`确认保留 ${chosen.length} 条`}<ArrowRight size={15}/></button></div></div></div><div className="small-conclusion"><p><strong>生成结果、选择采纳、保存成功。</strong>这三步各有自己的含义。</p><More id="organize" open={open}>为什么结果要分层</More></div></section>
}
export function Memory({open}:{open:Open}){
 const notes=[{id:1,title:'周末搬家',time:'刚刚',body:'给旺财换窝，买个拖把。'},{id:2,title:'上次的打包清单',time:'以前记过',body:'胶带、纸箱、记号笔。常用物品单独装。'},{id:3,title:'搬家公司备选',time:'以前存过',body:'先确认费用、上门时间和大件搬运范围。'}];
 const [chosen,setChosen]=useState([1,2]),[merged,setMerged]=useState(false),[source,setSource]=useState<number|null>(null);
 return <section className="memory-section" id="memory" data-scene="memory"><div className="section-wrap"><div className="memory-heading"><h2>原来，过去的自己<br/>已经做过一些准备。</h2><p className="section-lead">上次的打包清单、存过的搬家公司，都与今天有关。<br/>选好来源，合成“搬家准备”，零散的记录就有了下文。</p></div><MemoryMechanism chosen={chosen} merged={merged} source={source}/><div className="merge-demo" data-merged={merged}><div className="merge-source"><div className="demo-top"><span>挑选这次合并的来源</span><span>交互示意</span></div>{notes.map(n=><label aria-label={n.title} className={chosen.includes(n.id)?'source-note is-picked':'source-note'} key={n.id}><input type="checkbox" checked={chosen.includes(n.id)} onChange={()=>{setChosen(p=>p.includes(n.id)?p.filter(i=>i!==n.id):[...p,n.id]);setMerged(false);setSource(null)}}/><span><strong>{n.title}</strong><small>{n.body}</small></span><em>{n.time}</em></label>)}<p className="figure-note">AI 帮忙找候选，哪些属于这次主题，由你选。</p></div><div className="merge-connector"><span/><Layers size={25}/><span/></div><div className="merge-result"><div className="merge-label">主题</div><h3>搬家准备</h3>{merged?<div className="merge-output" aria-live="polite"><p>把这次搬家要用的资料收在一起：</p><ul>{notes.filter(n=>chosen.includes(n.id)).map(n=><li key={n.id}>{n.body}</li>)}</ul><div className="source-links">{notes.filter(n=>chosen.includes(n.id)).map(n=><button key={n.id} onClick={()=>setSource(n.id)}><Link2 size={12}/>{n.title}</button>)}</div>{source!==null&&<div className="source-peek"><button aria-label="关闭来源详情" onClick={()=>setSource(null)}><X size={14}/></button><strong>{notes.find(n=>n.id===source)?.title}</strong><p>{notes.find(n=>n.id===source)?.body}</p></div>}</div>:<div className="merge-empty"><p>选好来源，<br/>再整理成一份可回看的记录。</p><span>{chosen.length} 条已选 · 至少选 2 条</span></div>}<button className="solid-button" disabled={chosen.length<2} onClick={()=>{setMerged(true);setSource(null)}}>{merged?'重新生成演示':'试着合并'}<ArrowRight size={15}/></button><p className="merge-assurance"><ShieldCheck size={13}/>原记录保留，结果带着出处。</p></div></div><div className="small-conclusion"><p><strong>一条笔记解决眼前的事，一个主题连接持续的事。</strong></p><More id="memory" open={open}>主题、分类与层级的取舍</More></div></div></section>
}
export function Beyond({open}:{open:Open}){return <section className="section-wrap beyond-section" id="beyond" data-scene="beyond"><div className="beyond-heading"><p className="section-kicker">屏幕之外</p><h2>一次有用的帮助，<br/>还要经得起日常使用。</h2><p className="section-lead">网络不稳、结果晚到、建议不合心意，都会发生。<br/>把这些时刻照顾好，再回答：用户会留下来吗，会愿意付费吗？</p></div><Tabs defaultValue="trust" className="beyond-tabs"><TabsList className="story-tabs"><TabsTrigger value="trust">放心使用</TabsTrigger><TabsTrigger value="value">付费价值</TabsTrigger><TabsTrigger value="measure">验证价值</TabsTrigger></TabsList><TabsContent value="trust"><div className="beyond-panel"><div className="panel-title"><ShieldCheck size={28}/><h3>让用户放心，<br/>需要设计失败之后的路。</h3><p>把生成与保存分开，保护仍在编辑的内容。<br/>出错时，已有记录也应该好好地留在那里。</p><ReliabilityMechanism/><More id="reliability" open={open}>展开那些看不见的机制</More></div><dl className="reliability-rows"><div><dt>结果晚到了</dt><dd>保护刚写的草稿，避免覆盖。</dd><span>保存边界</span></div><div><dt>又点了一次</dt><dd>避免重复创建同一份记录。</dd><span>重复处理</span></div><div><dt>一个能力失败了</dt><dd>其他结果继续可用。</dd><span>局部恢复</span></div><div><dt>历史资料不足</dt><dd>说明不足，停止编造。</dd><span>可信来源</span></div></dl></div></TabsContent><TabsContent value="value"><div className="beyond-panel"><div className="panel-title"><Sparkles size={28}/><h3>“这次真的帮到我”，<br/>是付费理由的起点。</h3><p>先完成一次有用的体验，再研究持续服务的价值。这里保留商业判断，等待用户行为来验证。</p><span className="hypothesis">商业假设 · 尚待验证</span><More id="business" open={open}>啊哈时刻与付费节点</More></div><div className="value-path"><div><span>第一次记录</span><strong>先让用户顺利记下来</strong><p>帮助发生之前，价值还很抽象。</p></div><div className="value-highlight"><span>发现旧资料 / 保存有用结果</span><strong>“原来，这条记录还能这样用。”</strong><p>候选的啊哈时刻。</p></div><div><span>再次使用同类帮助</span><strong>持续节省精力，才有持续付费的可能</strong><p>研究订阅、额度和能力分层。</p></div></div></div></TabsContent><TabsContent value="measure"><div className="beyond-panel"><div className="panel-title"><Layers size={28}/><h3>生成了多少，<br/>还不足以说明有用。</h3><p>要继续看用户有没有采纳、有没有保存、后来有没有再用上。让行为记录回答具体的产品问题。</p><span className="hypothesis">验证方案 · 非真实运营数据</span><More id="measurement" open={open}>埋点与后台应该怎样设计</More></div><div className="measure-path">{[['记录完成','用户有没有顺利留下内容？'],['结果采用','AI 帮助是否值得被保存？'],['再次使用','旧记录是否重新派上用场？'],['持续付费','节省的精力是否值得长期付费？']].map(([a,b],i)=><div key={a}><span>{i+1}</span><div><strong>{a}</strong><p>{b}</p></div></div>)}</div></div></TabsContent></Tabs><div className="extra-reading"><button onClick={()=>open('globalization')}><span><strong>走向更多地区，先改变哪些默认假设？</strong><small>语言、日期、输入方式与本地服务 · 规划方向</small></span><ArrowUpRight size={20}/></button><button onClick={()=>open('sources')}><span><strong>这篇故事的材料与版本</strong><small>设计初衷、当前实现、仍待验证的判断</small></span><ArrowUpRight size={20}/></button></div></section>}
export function Ending({open}:{open:Open}){return <section className="ending"><div className="ending-inner"><ClosingNote/><p>这个产品想带来的改变，其实很朴素。</p><h2>少一点整理的负担。<br/>多一点事情有着落的感觉。</h2><p className="ending-copy">把复杂的 AI 能力，放进一次次具体的小帮助里。<br/>让一条记录，从“存着”走向“用上”。</p><button onClick={()=>open('sources')} className="text-link">读完故事，再看看依据<ArrowUpRight size={16}/></button></div></section>}
